@startuml
'https://plantuml.com/class-diagram

namespace Player{
class PlayerManager{
-void Swim()
}
note left of PlayerManager : ここだけでUpdateとかを行う

namespace Input{
class KeyInputMoveProvider{
}
interface IInputMoveProvider{
+bool InputAhead()
+bool InputLeft()
+bool InputRight()
+bool InputBack()
}
}
interface IPushable{
+void Push(float value)
}
}

namespace Enemy{
class RipCurrentManager{
}
}

Player.Input.KeyInputMoveProvider..|>Player.Input.IInputMoveProvider
Enemy.RipCurrentManager..|>Player.IPushable : プレイヤーを波で押す
Player.PlayerManager-u->Player.IPushable
Player.PlayerManager-u->Player.Input.IInputMoveProvider

@enduml